spring.application.name=spring-boot

#spring.datasource.url=jdbc:postgresql://localhost:5432/users
#spring.datasource.username=
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true

spring.data.mongodb.uri=mongodb://localhost
spring.data.mongodb.database=users
spring.threads.virtual.enabled=true
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
spring.data.mongodb.auto-index-creation=true